lines = [
"import pandas as pd",
"import os",
"import re",
"from openpyxl import Workbook",
"from openpyxl.styles import Font, PatternFill, Alignment",
"from openpyxl.chart import BarChart, Reference",
"from docx import Document",
"from docx.shared import Inches",
"from docx.dml.color import RGBColor as DocxRGB",
"from pptx import Presentation",
"from pptx.util import Inches as PInches, Pt as PPt",
"from pptx.chart.data import ChartData",
"from pptx.enum.chart import XL_CHART_TYPE",
"from lxml import etree",
"",
"",
"def set_textbox(shape, left, top, width, height):",
"    shape.left   = int(PInches(left))",
"    shape.top    = int(PInches(top))",
"    shape.width  = int(PInches(width))",
"    shape.height = int(PInches(height))",
"",
"",
"def add_text_to_placeholder(tf, text, font_size=16, bold=False):",
"    from pptx.oxml.ns import qn as pqn",
"    from lxml import etree as et",
"    txBody = tf._txBody",
"    bodyPr = txBody.find(pqn('a:bodyPr'))",
"    if bodyPr is None:",
"        bodyPr = et.SubElement(txBody, pqn('a:bodyPr'))",
"    for tag in ['a:noAutofit', 'a:spAutoFit', 'a:normAutofit']:",
"        el = bodyPr.find(pqn(tag))",
"        if el is not None:",
"            bodyPr.remove(el)",
"    et.SubElement(bodyPr, pqn('a:normAutofit'))",
"    bodyPr.set('wrap', 'square')",
"    tf.text = text",
"    for para in tf.paragraphs:",
"        for run in para.runs:",
"            run.font.size = PPt(font_size)",
"            run.font.bold = bold",
"",
"",
"def add_bullet_placeholder(tf, findings, font_size=16):",
"    from pptx.oxml.ns import qn as pqn",
"    from lxml import etree as et",
"    txBody = tf._txBody",
"    bodyPr = txBody.find(pqn('a:bodyPr'))",
"    if bodyPr is None:",
"        bodyPr = et.SubElement(txBody, pqn('a:bodyPr'))",
"    for tag in ['a:noAutofit', 'a:spAutoFit', 'a:normAutofit']:",
"        el = bodyPr.find(pqn(tag))",
"        if el is not None:",
"            bodyPr.remove(el)",
"    et.SubElement(bodyPr, pqn('a:normAutofit'))",
"    bodyPr.set('wrap', 'square')",
"    tf.clear()",
"    for i, finding in enumerate(findings):",
"        para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()",
"        para.text = finding",
"        para.level = 0",
"        for run in para.runs:",
"            run.font.size = PPt(font_size)",
"",
"",
"def get_chart_data(df, name='Dataset', df2=None, name2=None):",
"    numeric_cols = df.select_dtypes(include='number').columns.tolist()",
"    text_cols    = df.select_dtypes(exclude='number').columns.tolist()",
"    label_col    = text_cols[0] if text_cols else None",
"    num_col      = numeric_cols[0] if numeric_cols else None",
"    if not label_col or not num_col:",
"        return [], {}",
"    g1 = df.groupby(label_col)[num_col].sum().reset_index()",
"    g1.columns = ['Category', name]",
"    if df2 is not None and name2 is not None:",
"        numeric_cols2 = df2.select_dtypes(include='number').columns.tolist()",
"        text_cols2    = df2.select_dtypes(exclude='number').columns.tolist()",
"        label_col2    = text_cols2[0] if text_cols2 else None",
"        num_col2      = numeric_cols2[0] if numeric_cols2 else None",
"        if label_col2 and num_col2:",
"            g2 = df2.groupby(label_col2)[num_col2].sum().reset_index()",
"            g2.columns = ['Category', name2]",
"            merged = pd.merge(g1, g2, on='Category', how='outer').fillna(0)",
"            merged = merged.sort_values('Category').reset_index(drop=True)",
"            categories = merged['Category'].astype(str).tolist()",
"            series = {name: merged[name].tolist(), name2: merged[name2].tolist()}",
"            return categories, series",
"    g1 = g1.sort_values('Category').reset_index(drop=True)",
"    categories = g1['Category'].astype(str).tolist()",
"    series = {name: g1[name].tolist()}",
"    return categories, series",
"",
"",
"def build_excel_chart(wb, categories, series, chart_title):",
"    hdr_font = Font(bold=True, size=11, col